spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ticketnest?currentSchema=public&timezone=UTC
    username: ticketnest
    password: ticketnest_Admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

spring doc:
  swagger-ui:
    path: /swagger